config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :routes
  root 'application#index'
  
  resources :route_search, only: %i(index)

end

app/models/route.rb
class Route < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource)
    route_search_index_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/route_search_controller.rb
class RouteSearchController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)
    if @route.save
      head :ok
    else
      head :ng
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #以下で出発地、目的地とユーザーの情報を一緒に保持、データベース格納用
    def route_params
      params.require(:route).permit(:start, :goal, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/route_search_helper.rb
module RouteSearchHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/application/index.html.1.erb
<!--古いファイル，使わない12/1514時土屋-->
<FONT size="1">
    <div id="site-box">
    <div id="map" style="width: 800px; height: 600px;"></div>
    <div id="information">
        <input id="origin" type="textbox" value="大岡山駅" size="40" ><br />
        <input id="destination" type="textbox" value="石川台駅" size="40" ><br />
        <input type="button" value="SEARCH" onclick="searchRoute()">
    </div>
    <%= form_for(Route.new, data: { remote: true }) do |f| %>
       <%= f.text_field :start %><br>
       <%= f.text_field :goal %>
       <%= f.submit %>
    <% end %>
<!--        <div id="mark">
    <input type="button" value="Marker" onclick="plotLoop((route_result.length-1), 0)">
    <br>   -->
    <input type="button" value="Marker+" onclick="plotLoop1(2)">
    <br>
    <input type="button" value="DUMP" onclick="dumpStrView(2)">
    </div>
    </div>
</FONT>

app/views/application/index2.html.erb
<div class='bg-color-navy'>
<!-- ログインしていないときログインボタンを表示>
<!-- ログインしたらログアウトボタンを表示-->
<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>
<div style="text-align:center">
<img src="https://dl.dropboxusercontent.com/u/70372576/Lente.png" width="300" height="190" alt="">
</div>
<P Align="center"><font size="6">Lente  -レンテ-</font>
<P Align="center"><font size="5">スペイン語で「レンズ」という意味。</font>
<P Align="center"><font size="5">見えづらい方の世界を明るくします。</font>
<P Align="center"><font size="5"><font color="#ffff00">Lenteは</font></P>
<P Align="center"><font size="5"><font color="#ffff00">事前に目的地を設定し、地図情報をスムーズに調べるためのサービスです。</font></P>
<P Align="center"><font size="5"><font color="#ffff00">目的地までの経路や経路の周辺の建物の様子を調べることが出来ます。</font></P>

<P Align="center"><font size="4">お年寄りの方、道に迷いやすい方や、</P>
<P Align="center">例えば、以下のような弱視の方にもご利用いただけます。</P>
<style type="text/css">
.content {
text-align:center;
}

.content span {
display:inline-block;
text-align:left;
}
</style>

<p class="content"><span>
●建物に近づいても看板の文字が見えない。  <br>
●事前にルート上の目印を数えて覚えておく。<br>
●視覚障がい者のためのヘルパーなしで出かける。
</span></p>

<P Align="center">また</P>
<style type="text/css">
.content {
text-align:center;
}

.content span {
display:inline-block;
text-align:left;
}
</style>

<p class="content"><span>
●普段からビジネスで出かける用事が多い。        <br>
●毎回、行き方を徹底的に調べる。                <br>
●複数のアプリを使っている。                    <br>
</span></p>

<br>
<P Align="center">でも<br/>
<style type="text/css">
.content {
text-align:center;
}

.content span {
display:inline-block;
text-align:left;
}
</style>

<p class="content"><span>
<P Align="center">○待ち合わせの場所までの道順をしっかり調べても、</P>
<P Align="center">当日ちょっと道を間違えたことに気づかずに迷ってしまった！！</P>
<P Align="center">○明日の道順を調べるのが大変だ。時間がない！</P>
</span></p>
<P Align="center">そんなことはありませんか？<br/>

<br><div style="margin-top:3em">
<P><P Align="center">Lenteは</P></P></div>
<P Align="center">簡単な操作で、実際の外出をイメージしやすい経路情報を提供し</P>
<P Align="center">あなたのスムーズな外出をサポートします。</P>

<P Align="center">Lenteと一緒に出かけてみませんか？</P></font>

<br><div style="margin-top:3em">
<P Align="center"><font size="5">サービスの概要 </font></P></div>

<style type="text/css">
.content {
text-align:center;
}

.content span {
display:inline-block;
text-align:left;
}
</style>

<p class="content"><span>
<P Align="center"><font size="5"> ①経路周辺の建物の写真が一覧で把握できます</P></font>
<P Align="center"><font size="4"> また次の曲がり角まで何mか、曲がり角でどの方向に曲がるのかテキストで表示するため、音声情報として利用することも出来ます。</font></P>

<P Align="center"><font size="5">②音声や画像付き地図データを表示します </font></P>
<P Align="center"><font size="4">事前に、出発地と目的地を入力し経路を検索できます。 </P>
<P Align="center">検索で得られた経路周辺情報はスマートフォンにダウンロードし、
確認することもできます。</P>
</span></p>

<P Align="center">※あくまでも、目の見えにくい人の歩行の補助になるもので、
現在地と目的地とのルート補整を行うものではありません。 </font></P>


<br><div style="margin-top:3em">
<P Align="center"><font size="5">サービスのイメージをこちらの動画でご確認ください。</P></div>
<div style="text-align: center;">
<iframe width="560" height="315" src="https://www.youtube.com/embed/BpGNa22Z3UQ"></iframe>
</div>
</div>
</div>

app/views/application/new.html.erb
<p><font size="7">Lente</font></p>
<!--mapと検索ボタン部分のdiv-->
<div id="mapandkensaku">
    <!--地図本体の描画-->
    <div id="map" style="width: 700px; height: 450px;"></div>
    <!--出発地の文字とボタンの描画-->
    <p>出発地</p>
    <input id="start" type="textbox" size="40" value="大岡山駅"><br>
    <!--目的地の文字とボタンの描画-->
    <p>目的地</p>
    <input id="end" type="textbox" size="40" value="駒沢大学駅"><br>
    <!--一気に2つやることにしました一応残しておく-->
    <!--ルート検索ボタン-->
    <!--<input type="button" value="ルート検索" onclick="calcRoute()"><br>-->
    <!--案内図作成ボタン-->
    <!--<input type="button" value="案内図作成" onclick="route_hyouzi()">-->
    <input type="button" value="ルート検索" onclick="calcRoute()">
</div>
<!--検索結果，ルート案内部分のdiv-->
<div id="annai">
    <div id="directionsPanel" style="width: 500px; height: 500px"></div>
</div>
<!--lente本体がここに来るはず…-->
<div id="annaizu"style="width:700px; height:500px; overflow:auto;">
    <!--ここにif文を使って写真，案内文の順でステップごとに表示させたい-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="css/freelancer.min.css" rel="stylesheet">
    <link href="css/lente.css" rel="stylesheet">
    <script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDGqAri4cCw1hQu66nIEjT5d-uk8cV_XD0&libraries=places&geometry" charset="utf-8"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--スタイル追加-->
    <!--
        <style type="text/css">
            body {
                font-size: 120%;
                /*line-height: 100%;*/
                width: 80%;
            }
            #mapandkensaku {
                float: left;
                line-height: 1%;
                width:70%; 
                height:100%;
            }
            #annai {
                float: right;
                width:30%;
                height:100%;
            }
    </style>
    -->

  </head>
   <!--headerコピペ-->
  <body id="page-top" onload="initialize()" link="##ffff00" vlink="##ffff00" alink="##ffff00">
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <!--<a class="navbar-brand js-scroll-trigger" href="#page-top">Lente</a>-->
        <img class="img-fluid mb-5 d-block mx-auto" src="img/lente2.png" alt="">
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#portfolio">Lenteとは</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#How to use">使い方</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#contact">お問い合わせ</a>
            </li>
            <% if user_signed_in? %>
          <li class="nav-item mx-0 mx-lg-1">
                 <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class:"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"%>
               <% end %>
          </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/freelancer.min.js"></script>

  </body>

</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>      
<head>
  <title>Workspace</title>
  <script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDGqAri4cCw1hQu66nIEjT5d-uk8cV_XD0&libraries=places&geometry" charset="utf-8"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--スタイル追加-->
  <style type="text/css">
            body {
                font-size: 120%;
                /*line-height: 100%;*/
                width: 80%;
            }
            #mapandkensaku {
                float: left;
                line-height: 1%;
                width:70%; 
                height:100%;
            }
            #annai {
                float: right;
                width:30%;
                height:100%;
            }
        </style>
</head>
<body onload="initialize()" link="#ffff00" vlink="#ffff00" alink="##ffff00">

<%= yield %>

</body>
</html>

app/views/route_search/index.html.erb
<style type="text/css">
  body {
    font-size: 100%;
    width: 80%;
    margin-top: 150px;
  }
  #hidari {
    float: left;
    width:70%;
  }
  #annaizu {
   float: right;
   width:30%;
  }
  #nyuuryoku{
    float: left;
    width:30%;
  }
  #kensaku_button{
    float:right;
    width:40%;
  }
</style>
<!--<% if user_signed_in? %>-->
<!--  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>-->
<!--<% end %>-->
<div id="hidari">
  <div id="nyuuryoku">
    <!--出発地の文字とボタンの描画-->
    <p>出発地</p>
    <input id="start" type="textbox" size="80" value="大岡山駅" style="width:10em;height:1em;font-size:200%"><br>
    <!--目的地の文字とボタンの描画-->
    <p>目的地</p>
    <input id="end" type="textbox" size="80" value="駒沢大学駅" style="width:10em;height:1em;font-size:200%"><br>
  </div>    
  <div id="kensaku_button">
    <input type="button" value="ルート検索" onclick="calcRoute()" style="width:6em;height:5em;font-size:150%">
    <input type="button" value="印刷する" onclick="window.print();" style="width:6em;height:5em;font-size:150%">
  </div>
　<div id="map_annaiban">
    <!--地図本体の描画-->
    <div id="map" style="width: 600px; height: 500px;"></div>
    <div id="directionsPanel" style="width: 700px; height: 1200px"></div>
  </div>
</div>
<div id="annaizu"style="width:200px;"></div>
<input type='hidden' id='user_id', value="<%= current_user.id %>">

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </div>
  <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_field :goal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Routes</h1>
<!-- 顧客の入力情報をデータベースとして保持。-->
<!-- "/routes" で一覧でみれます-->
<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>User</th>
      <th>Start</th>
      <th>Goal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.created_at %></td>
        <td><%= route.user_id %></td>
        <td><%= route.start %></td>
        <td><%= route.goal %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @route.start %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @route.goal %>
</p>

<p>
  <strong>作成日時:</strong>
  <%= @route.created_at %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>